name: Github Actions Workflow
on: [push]
jobs:
  # Stage 1: Initialize the pipeline.
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Workflow
        run: echo "Initializing pipeline and preparing environment..."

  # Stage 2: Build
  build:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build Android App
        run: ./gradlew assembleDebug